when:
  event: [push, pull_request, manual]

steps:
  - name: validate-authelia-config
    image: ghcr.io/authelia/authelia:latest
    commands:
      - authelia validate-config --config authelia/configuration.yaml