server:
  address: tcp://0.0.0.0:9091/
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true
totp:
  issuer: "segmueller.org"
  period: 30
  skew: 1
authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128
access_control:
  default_policy: deny
  rules:
    - domain:
        - "*.segmueller.org"
        - "segmueller.org"
      policy: two_factor
session:
  name: authelia_session
  same_site: lax
  expiration: 7h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: "segmueller.org"
      authelia_url: "https://authelia.segmueller.org"
      default_redirection_url: "https://segmueller.org"
regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notifications.txt
